{% set name = "mp_time_split" %}
{% set version = "0.2.0" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mp-time-split-{{ version }}.tar.gz
  sha256: efc4f29608d3470888b371dc1e999e877d08b88621945d1fe5a2f2696b19ca40

build:
  number: {{ build_num }}

outputs:
  - name: {{ name }}
    build:
      entry_points:
        - mp_time_split = mp_time_split.core:run
      number: 1
      noarch: python
    script: build_base.sh

    requirements:
      host:
        - pip
        - setuptools-scm
        - python {{ python_min }}
      run:
        - matminer
        - pymatgen
        - scikit-learn
        - pybtex
        - typing-extensions
        - python >={{ python_min }}
        - importlib-metadata
    test:
      imports:
        - mp_time_split
      commands:
        - pip check
        - mp_time_split --help
      requires:
        - pip

  - name: {{ name.replace("_", "-") }}
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - mp_time_split

about:
  home: https://github.com/sparks-baird/mp-time-split
  summary: Use Materials Project time-splits for generative modeling benchmarking.
  dev_url: https://github.com/sparks-baird/mp-time-split
  license: MIT
  license_file: LICENSE.txt
  doc_url: mp-time-split.readthedocs.io

extra:
  recipe-maintainers:
    - sgbaird
